---
title: "MCMC demo"
author: "Juho Timonen"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
#  pdf_document:
#    toc: true     
vignette: >
  %\VignetteIndexEntry{MCMC demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```


```{r setup}
require(mc2)
require(ggplot2)
require(ggpubr)
```

## Target distribution
We begin by defining a target log posterior density.
```{r grid, fig.width = 6, fig.height = 6}
log_prob <- function(x){donut(x)}
log_prob(c(2,3))
```

## Metropolis algorithm
First we sample using the Metropolis algoritm.
```{r metropolis, fig.width = 7.2, fig.height = 2.8}
SIG   <- c(0.1,0.5,1.0)
ITER  <- rep(1000, 3)
PLT   <- list()
for(j in 1:3){
  x0     <- stats::rnorm(2)
  sig    <- SIG[j]
  iter   <- ITER[j]
  chain  <- metropolis(log_prob, x0, iter, sig)
  title  <- paste0('Metropolis, sig = ', sig, ', iter = ', iter)
  p      <- plt.surface(donut, title = title)
  PLT[[j]] <- add.path(p, chain$x, lines = FALSE, alpha = 0.3)
}

ggarrange(plotlist = PLT, nrow = 1, ncol = 3)
```
