---
title: "MCMC tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MCMC tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
require(mc2)
set.seed(123)
```

We begin by defining a target log posterior density and a grid for plotting.
```{r grid, fig.width = 6, fig.height = 6}
t        <- seq(-5, 5, by=0.1)
log_prob <- function(x){peaks(x)}
z_fun    <- function(t1,t2){peaks(cbind(t1,t2))}
z        <- outer(t, t, z_fun)
```

First we sample using the Metropolis algoritm.
```{r metropolis, fig.width = 6, fig.height = 6}
# Sample
iter  <- 5000
x0    <- stats::rnorm(2)
sig   <- 0.5
chain <- metropolis(log_prob, x0, iter, sig)
x     <- chain$x

# Plot
contour(t,t,z, main = paste(iter, 'samples'), xlim=c(-5,5), ylim=c(-5,5))
points(x[,1], x[,2], pch = 20, col = "firebrick")
#legend('topright', legend=c('log posterior', 'MCMC samples'))
```
